name: Rust

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rustfmt:
    name: 🗊 Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  lint:
    name: 🚨 Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --all-targets -- -D warnings

  test:
    name: ✅ Test Suite
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports:
          - 8001:5432
      redis:
        image: redis:7
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
        with:
          key: sqlx-0.6.2
      - name: Install sqlx-cli
        run:
          cargo install sqlx-cli
          --version=0.6.2
          --features rustls,postgres
          --no-default-features 
          --locked
      - name: Migrate database
        run: |
          sudo apt-get install libpq-dev -y
          sqlx database create
          sqlx migrate run
      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-nextest
          locked: true
      - uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run --retries 5 --workspace --failure-output final

  security_audit:
    name: 👮 Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache cargo bin
        uses: actions/cache@v1
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-audit
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
